version: "3.9"
services:
  hook-app:
    container_name: hook-app
    build:
      context: .
      target: production
    command: npm start
    ports:
      - "8081:8081"
    env_file:
    - web-variables.env
    networks:
      - app-network
    volumes:
      - ~/node_app/hook-root/assignment-3-realtime-web-application/src:/app/src
      - ~/node_app/hook-root/assignment-3-realtime-web-application/public:/app/public

  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/node_app/web-root:/var/www/html
      - ~/node_app/nginx-conf:/etc/nginx/conf.d
      - ~/node_app/certbot-etc:/etc/letsencrypt
      - ~/node_app/certbot-var:/var/lib/letsencrypt
      - ~/node_app/dhparam:/etc/ssl/certs
    depends_on:
      - hook-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge